# How to get latest...
# 1 Keep updating the file. Seems easiest and best.
# 2 Look for patterns in releases,.. not really
# 3 curl the page then grep the href matching pattern - complicated, should account for when it does not work and you ahve to fix it
# 4 use some package manager...
